# -*- coding: utf-8 -*-
"""gastro+ai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yAObuVs9jSa0yAKHg-Ma96_IVhpa1Fr0
"""

import pandas as pd #pd is nickname for pandas
df=pd.read_csv('DATA.csv')

type(df)

df





df = pd.read_csv("DATA.csv", index_col=False)
df = df.loc[:, ~df.columns.str.contains('Unnamed')]

df

x=df.iloc[ : , :-1]

x

y=df.iloc[:,-1]

y

x=x.values

x

y=y.values

y

#step-4
from sklearn.preprocessing import LabelEncoder # import the label encoder library from sklear.preprocessing
le=LabelEncoder() # the  LabelEncoder is used to encode the output columns.
y=le.fit_transform(y)

y

x

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

x_train

x_test

y_train



y_test

#step-6:feature scaling
from sklearn.preprocessing import StandardScaler

sc = StandardScaler(with_mean=False)  # don't subtract mean
x_train[:,0:] = sc.fit_transform(x_train[:,0:])
x_test[:,0:] = sc.transform(x_test[:,0:])

x_train

x_test

#step-7:applying algorithum to the data and train the AI-model
from sklearn.linear_model import LogisticRegression #logistic regression class is imported by sklearn
Classifier=LogisticRegression()#create a variable called classifier and the LogisticRegression is used to train pour AI-model
Classifier.fit(x_train,y_train)

LogisticRegression()

y_pred=Classifier.predict([[1.40217926,  1.57167735, 37.90218477,  6.82278848 ]])

y_pred